// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - XMBASEMessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface XMBASEMessageRoot : GPBRootObject
@end

#pragma mark - XMBASERequest

typedef GPB_ENUM(XMBASERequest_FieldNumber) {
  XMBASERequest_FieldNumber_URL = 1,
  XMBASERequest_FieldNumber_Body = 2,
  XMBASERequest_FieldNumber_Token = 3,
  XMBASERequest_FieldNumber_Version = 4,
  XMBASERequest_FieldNumber_OsName = 5,
  XMBASERequest_FieldNumber_OsVersion = 6,
};

@interface XMBASERequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite, copy, null_resettable) NSData *body;

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

/** ios，android */
@property(nonatomic, readwrite, copy, null_resettable) NSString *osName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *osVersion;

@end

#pragma mark - XMBASEResponse

typedef GPB_ENUM(XMBASEResponse_FieldNumber) {
  XMBASEResponse_FieldNumber_Status = 1,
  XMBASEResponse_FieldNumber_StatusTxt = 2,
  XMBASEResponse_FieldNumber_Body = 3,
};

@interface XMBASEResponse : GPBMessage

@property(nonatomic, readwrite) int32_t status;

@property(nonatomic, readwrite, copy, null_resettable) NSString *statusTxt;

@property(nonatomic, readwrite, copy, null_resettable) NSData *body;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
