// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Xm.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - XMTestXmRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface XMTestXmRoot : GPBRootObject
@end

#pragma mark - XMTestTestRequest

typedef GPB_ENUM(XMTestTestRequest_FieldNumber) {
  XMTestTestRequest_FieldNumber_Requestid = 1,
  XMTestTestRequest_FieldNumber_Index = 2,
  XMTestTestRequest_FieldNumber_URL = 3,
};

@interface XMTestTestRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *requestid;

@property(nonatomic, readwrite) int32_t index;

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@end

#pragma mark - XMTestTestResponse

typedef GPB_ENUM(XMTestTestResponse_FieldNumber) {
  XMTestTestResponse_FieldNumber_ErrorMsg = 1,
  XMTestTestResponse_FieldNumber_ErrorCode = 2,
  XMTestTestResponse_FieldNumber_ListArray = 3,
};

@interface XMTestTestResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMsg;

@property(nonatomic, readwrite) int64_t errorCode;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
