# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'



target 'XmNetworkSDK' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XmNetworkSDK
   pod 'Protobuf', '~> 3.3.0'
 	 pod 'AFNetworking', '~> 3.1.0'
   pod 'CocoaLumberjack', '~> 3.2.0' 

  target 'XmNetworkSDKTests' do
    inherit! :search_paths
    # Pods for testing
   pod 'Protobuf', '~> 3.3.0'
 	 pod 'AFNetworking', '~> 3.1.0'
   pod 'CocoaLumberjack', '~> 3.2.0'     
  end

end
